#[derive(PartialEq, Eq)]
enum ELEMENT {
    SOURCE,
    SPLITTER,
    BEAM,
    EMPTY,
}

struct Puzzle {
    contents: String,
    result1: usize,
    result2: usize,
}
fn char_2_element(c: char) -> ELEMENT {
    match c {
        'S' => ELEMENT::SOURCE,
        '^' => ELEMENT::SPLITTER,
        _ => ELEMENT::EMPTY,
    }
}
fn element_2_char(e: &ELEMENT) -> char {
    match e {
        ELEMENT::BEAM => '|',
        ELEMENT::EMPTY => '.',
        ELEMENT::SOURCE => 'S',
        ELEMENT::SPLITTER => '^',
    }
}

impl Puzzle {
    fn new(filename: &str) -> Puzzle {
        use crate::ELEMENT::*;

        let contents: String = std::fs::read_to_string(filename).expect("File not found");

        let mut first_line: Vec<ELEMENT> = vec![];
        let mut second_line: Vec<ELEMENT> = vec![];

        let mut lineit = contents.lines().into_iter();

        let mut beam_hit_splitter_count = 0;

        first_line = lineit
            .next()
            .unwrap()
            .chars()
            .map(|x| char_2_element(x))
            .collect();
        second_line = lineit
            .next()
            .unwrap()
            .chars()
            .map(|x| char_2_element(x))
            .collect();
        loop {
            // do tachyon beam physics :)  second line depends only on first line
            for (pos, element) in first_line.iter().enumerate() {
                match element {
                    SOURCE => {
                        second_line[pos] = BEAM; // source emits down beam
                    }
                    SPLITTER => { // do nothing 
                    }
                    BEAM => {
                        if second_line[pos] == EMPTY {
                            // propagate any beam down to empty space
                            second_line[pos] = BEAM;
                        } else if second_line[pos] == SPLITTER {
                            // except when it hits a splitter
                            // splitter creates beam left and right in same row
                            beam_hit_splitter_count += 1;
                            second_line[pos - 1] = BEAM; // propagate left beam from splitter down
                            second_line[pos + 1] = BEAM; // propagate right beam from splitter down
                        }
                    }

                    _ => {}
                }
            }
            let line: String = first_line.iter().map(|e| element_2_char(&e)).collect();
            println!("{}", line);
            //advance
            first_line = second_line;
            second_line = match lineit.next() {
                Some(v) => v.chars().map(|x| char_2_element(x)).collect(),
                None => {
                    break;
                }
            }
        }

        Puzzle {
            contents,
            result1: beam_hit_splitter_count,
            result2: 0,
        }
    }

    fn solve1(&mut self) {}
}

use std::{time::Instant, usize};

fn main() {
    println!("AoC 2025 Riddle 7");
    //let filename = "../7/test.txt";
    let filename = "../7/riddle.txt";
    let mut puzzle = Puzzle::new(filename);

    let start = Instant::now();
    puzzle.solve1();
    let elapsed = start.elapsed();
    println!("Result1: {}", puzzle.result1);
    println!("Millis: {} ms", elapsed.as_millis());
}
/*
--- Day 7: Laboratories ---

You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|

To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?

*/
